### ISSUE TITLE
Is it better to not separate these logs with an extra empty line?

### ISSUE THREAD

**Issue by ice1000** [Myriad-Dreamin/shiroa#60]
![image](https://github.com/Myriad-Dreamin/typst-book/assets/16398479/9c71daff-5848-4df3-992b-cc54b902da58)

Looks kinda too empty and does not make good use of the vertical space

**Comment by Myriad-Dreamin** [comment]
There is possibly some bug in the status logging. I will take a look.

**Comment by ice1000** [comment]
> There is possibly some bug in the status logging. I will take a look.

The logging code uses printing, and the Display impl of compiler messages use written. I suggest changing latter, it's in typst.ts

**Comment by Myriad-Dreamin** [comment]
Will be fixed in next publish~

**Comment by Myriad-Dreamin** [comment]
fixed in v0.1.5
