### ISSUE TITLE
How necessary is using tar.gz instead of zip?

### ISSUE THREAD

**Issue by ice1000** [Myriad-Dreamin/shiroa#62]
Is using `.tar.gz` for artifact an essential thing to do? Would it be very bad to upload using zip?

I'm working on making this to winget, which only works for zip rn, ref https://github.com/microsoft/winget-cli/issues/2899

**Comment by Myriad-Dreamin** [comment]
tar are more widely deployed on unix machines.

It is smarter to provide zip for win platforms and tar.gz for rest platforms.

**Comment by Myriad-Dreamin** [comment]
This is handled by cargo-dist with one-line effort:

https://github.com/Myriad-Dreamin/shiroa/blob/00bc5eb1044f6085569e352632bfcaae81e0117f/dist-workspace.toml#L13-L16
