### ISSUE TITLE
(1) Project Roadmap? (2) Does Typst Book Support 

### ISSUE THREAD

**Issue by dani-ko** [Myriad-Dreamin/shiroa#64]
Ditto issue's title:
1) Does Typst Book project have some roadmap, or maybe a tracking issue, or a commitment to some timeline?
2) Does Typst Book support Typst packages (https://github.com/typst/packages/tree/main), and if not, is there a plan to do so in the future?

Thank you very much in advance.

**Comment by Myriad-Dreamin** [comment]
> 1. Does Typst Book project have some roadmap, or maybe a tracking issue, or a commitment to some timeline?
> 2. Does Typst Book support Typst packages (https://github.com/typst/packages/tree/main), and if not, is there a plan to do so in the future?

1. https://myriad-dreamin.github.io/typst-book/#label-Not%20yet%20finished%20project
2. https://github.com/Myriad-Dreamin/typst-book/issues/63

**Comment by Myriad-Dreamin** [comment]
It is renamed to shiroa to satisfy the naming requirement of typst packages/templates, but I will do some improvement and introduce breaking change to make a nice start to a brand new template. The current interface haven't changed since typst v0.6.0, and we can do many things in a better way now.
