### ISSUE TITLE
Crash when building via Github Action (called `Option::unwrap()` on a `None` value)

### ISSUE THREAD

**Issue by TempContainer** [Myriad-Dreamin/shiroa#87]
The webpage renders correctly locally, but crashes during the build book phase when deployed to GitHub Pages via GitHub Actions. Here is my [GitHub Actions](https://github.com/TempContainer/typnotes/blob/main/.github/workflows/gh_pages.yml) setup. I don't understand Rust at all, and I can't figure out the fault location from the [full backtrace](https://github.com/TempContainer/typnotes/actions/runs/11320884164/job/31479109715) (it seems there might be a memory leak).
I have no idea where the problem lies. Any help would be appreciated.

**Comment by Myriad-Dreamin** [comment]
Could you fix the ubuntu image to `22.04`? It seems that GitHub doesn't create data directory for your image. Recent successful example: https://github.com/typst-doc-cn/tutorial/actions/runs/11325149261.

Specifically, the directory is missing:

![image](https://github.com/user-attachments/assets/3f1a260a-6653-4276-bf80-2f029a697d56)

```shell
data_dir | Some($XDG_DATA_HOME) or Some($HOME/.local/share)
```


Ref: https://docs.rs/crate/dirs/latest

**Comment by TempContainer** [comment]
Switching to 22.04 solved the problem. Thanks!

**Comment by Myriad-Dreamin** [comment]
Can also create these directory if not exists: https://github.com/Myriad-Dreamin/tinymist/actions/runs/11370334031/job/31629875480
