### ISSUE TITLE
Incorrect rendering of $macron()$

### ISSUE THREAD

**Issue by Sinofine** [Myriad-Dreamin/shiroa#91]
code:
```typst
#import "/book.typ": book-page

#show: book-page.with(title: "Hello, typst")
#let gal = math.op("Gal")
= Hello, typst

Sample page

For any $sigma in gal(macron(K) \/ K)$, $sigma(x)=x$ holds.
```
expected result(using `typst compile`):
![expected](https://github.com/user-attachments/assets/2afaad78-dece-4953-bb60-92b9da521a46)

or(using `tinymist preview`):
![expected2](https://github.com/user-attachments/assets/87228075-4c98-40e7-bcb8-3e80a84ab5fd)

actual result(using `shiroa serve` & `shiroa build`):
![actual](https://github.com/user-attachments/assets/3296b54e-b5b1-444d-a33a-6d0e02ae5d00)

Seems it cannot render $\bar{K}$ correctly.

build info
```
shiroa version 0.1.5
features: embedded_fonts

program-ver: 08b2b4c
program-rev: 08b2b4cb70463addcbe218d934f335ea1b21750e
program-build: x86_64-unknown-linux-gnu with opt level(3) at 2024-12-02T13:30:00.190119595Z

rustc-ver: 1.84.0-nightly
rustc-rev: da935398d582344c5b7689bd6632d8ec01b0c988
rustc-build: x86_64-unknown-linux-gnu-nightly with LLVM 19.1
```

MWE:
[test_shiroa_site.zip](https://github.com/user-attachments/files/18008923/test_shiroa_site.zip)

**Comment by Myriad-Dreamin** [comment]
The patch is included in v0.2.0-rc1
